### Variables
@url = http://localhost:3000/api/v1

@type = water
### Random Pokemon
GET {{ url }}/pokemon/random

### Spacifit Pokemon
GET {{ url }}/pokemon/5

### Random Pokemon Type
GET {{url}}/pokemon/random/{{type}}


### Add new pokemon
POST {{url}}/pokemon/add
Content-Type: application/json

{ 
    "id": 10,
    "name": "Caterpie",
    "type": "Bug"
}