### Variables
@url = http://localhost:3000/api/v1

@type = Fire

@id = 69d46500a9cc5b20ba236172



### pokemon by Id
GET {{ url }}/pokemon/byId{{id}}


### Random Pokemon
GET {{ url }}/pokemon/random

### Spacifit Pokemon
GET {{ url }}/pokemon/2

### Random Pokemon Type
GET {{url}}/pokemon/random/{{type}}


### Add new pokemon
POST {{url}}/pokemon/add
Content-Type: application/json

{ 
    "number": 11,
    "name": "Metapod",
    "type": "Bug"
}

### Get All Pokemon
 {{url}}/pokemon/


### Get Pokemon By Name
 {{url}}/pokemon/byName/ivysaur